#!/usr/bin/env php
<?php

require dirname(__DIR__) . '/autoload.php'; // goes up from vendor/bin/ to vendor/autoload.php

use NHRROB\WPFatalTester\FatalTester;

// Auto-detect plugin folder if no argument is given
$plugin = $argv[1] ?? basename(getcwd());

$tester = new FatalTester();
$tester->run([
    'plugin' => $plugin,
    'php' => ['8.1', '8.2'],
    'wp' => ['6.5', '6.6']
]);
